version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - shared_network
    ports:
      - 5432:5432

  server:
    container_name: server
    build: packages/server
    networks:
      - shared_network
    ports:
      - 8000:8000
    depends_on:
      - db
    # TODO: remove
    restart: on-failure

  # web:
  #   container_name: web
  #   build: packages/web
  #   networks:
  #     - shared_network
  #   ports:
  #     - 3000:3000

# Mac only (Linux/Windows benefit from network_mode: host)
# See https://docs.docker.com/desktop/mac/networking/#known-limitations-use-cases-and-workarounds
networks:
  shared_network: {}
