"""create_forests_table

Revision ID: 7ce2e71b8832
Revises: 
Create Date: 2022-03-02 06:32:46.063921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce2e71b8832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forests', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('forests', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forests')
    # ### end Alembic commands ###
